name: Construction d'un Projet

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  create-folder:
    name: Create folder on remote VM
    runs-on: debian-latest
    steps:
      - name: Create folder on remote VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build with Mavenssh-keygen -t rsa -b 4096 -C "your_email@example.com"
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml

# Uncomment the following steps if you need to publish to GitHub Packages
#      - name: Publish to GitHub Packages Apache Maven
#        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
