name: Construction d'un Projet

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  create-folder:
    name: Create folder on remote VM
    runs-on: ubuntu-latest
    steps:
      - name: Create folder on remote VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 172.16.1.242
          username: root
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            mkdir -p /path/to/your/folder
            ls -al /path/to/your/folder

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml
